### ISSUE TITLE
appKill support

### ISSUE THREAD

**Issue by codeskyblue** [anonymous5l/iConsole#1]
Ref project: https://github.com/troybowman/dtxmsg

**Comment by anonymous5l** [comment]
这里面写了需要越狱后的iPhone所以这个功能我觉得openssh加上一些简单的linux命令就可以实现

**Comment by codeskyblue** [comment]
不是的，这个不需要越狱就可以。只需要按钮DTXMessage的格式，通过跟服务 com.apple.instruments.remoteserver 通信就可以了。就是格式有点复杂。不过感觉跟大佬现在的工作比起来，实在不能算复杂。

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/89012274-81f86d00-d344-11ea-88f7-081712a55e62.png)

**Comment by anonymous5l** [comment]
确实很有意思 现在已经支持了
